version: "3.8"
services:
  db05:
    image: ubuntu_mysql:1.0 # Use the custom MySQL image built from Ubuntu base
    environment:
      MYSQL_ROOT_PASSWORD: jsbdK76WS8aR5  # Set MySQL root password
      # Optionally, uncomment and set these environment variables
      # MYSQL_DATABASE: testdb1
      # MYSQL_USER: appuser
      # MYSQL_PASSWORD: hslDG82fR9n1F
    volumes:
      - /opt/share/db/db05/db05_var_lib_mysql:/var/lib/mysql  # Persistent MySQL data
      - /opt/share/db/db05/db05_var_log_mysql:/var/log/mysql  # Log directory
      - /opt/share/jumper_dba/mysql-confs/db05:/etc/mysql  # Custom MySQL configuration file
    networks:
      - my_overlay_network
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Limit MySQL container to 2 CPUs
          memory: "3G"  # Limit MySQL container to 3GB of RAM
        reservations:
          cpus: "1.0"  # Reserve 1 CPU for MySQL container
          memory: "1G"  # Reserve 1GB of RAM for MySQL container
    ports:
      - "3126:3306"  # Port forwarding for external access to MySQL
networks:
  my_overlay_network:
    external: true
