version: "3.8"
services:
  app014:
    image: app014:2.0
    volumes:
      - /opt/share/apps/app014/proprofsflashcards.com:/var/www/web/proprofsflashcards.com
      - ./nginx/app014/confs:/etc/nginx/conf.d
      - /opt/share/apps/logs/app014:/var/log/nginx
    networks:
      - my_overlay_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"  # Limit to 2 CPUs
          memory: "2G"  # Limit to 2GB of RAM
        reservations:
          cpus: "1.0"  # Minimum of 1 CPU
          memory: "1G"  # Minimum of 1GB of RAM

networks:
  my_overlay_network:
    external: true
