version: "3.8"
services:
  app013:
    image: app013:1.0
    volumes:
      - /opt/share/apps/app013/proprofsgames.com:/var/www/web/proprofsgames.com
      - ./apache-confs/app013/confs:/etc/apache2/conf.d
      - /opt/share/apps/logs/app013:/var/log/apache2
    networks:
      - my_overlay_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"  # Limit to 2 CPUs
          memory: "3G"  # Limit to 3GB of RAM
        reservations:
          cpus: "1.0"  # Minimum of 1 CPU
          memory: "1G"  # Minimum of 1GB of RAM
networks:
  my_overlay_network:
    external: true
